#!/bin/bash
#
# Generate Professional Client Forensics Report
# Usage: ./generate-client-report.sh <TOKEN_ADDRESS> <CLIENT_NAME> [SEED]
#

set -e

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

# Validate arguments
if [ $# -lt 2 ]; then
    echo -e "${RED}Usage: $0 <TOKEN_ADDRESS> <CLIENT_NAME> [SEED]${NC}"
    echo ""
    echo "Example:"
    echo "  $0 0x123...abc AcmeCorp 12345"
    echo ""
    echo "Arguments:"
    echo "  TOKEN_ADDRESS - Contract address of token to analyze"
    echo "  CLIENT_NAME   - Client name for output directory"
    echo "  SEED          - Optional: Seed for reproducibility (default: current time)"
    exit 1
fi

TOKEN_CONTRACT="$1"
CLIENT_NAME="$2"
SEED="${3:-$(date +%s)}"

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

# Output directory
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT_DIR="$PROJECT_ROOT/reports/${CLIENT_NAME}_${TIMESTAMP}"

# Print header
echo -e "${BLUE}=============================================${NC}"
echo -e "${BLUE}  Professional Client Forensics Report${NC}"
echo -e "${BLUE}=============================================${NC}"
echo ""
echo -e "${YELLOW}Client:${NC} $CLIENT_NAME"
echo -e "${YELLOW}Token:${NC} $TOKEN_CONTRACT"
echo -e "${YELLOW}Seed:${NC} $SEED (for reproducibility)"
echo -e "${YELLOW}Output:${NC} $OUTPUT_DIR"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Check for extended script
if [ ! -f "$PROJECT_ROOT/boomscan_forensics_extended.py" ]; then
    echo -e "${RED}Error: boomscan_forensics_extended.py not found${NC}"
    exit 1
fi

# Check for dependencies
echo -e "${GREEN}Checking dependencies...${NC}"
python3 -c "import requests" 2>/dev/null || {
    echo -e "${YELLOW}Warning: requests not installed. Install with: pip3 install requests${NC}"
}

# Run comprehensive analysis
echo -e "${GREEN}Running comprehensive analysis...${NC}"
echo -e "${YELLOW}(This may take 30-60 seconds)${NC}"
echo ""

cd "$PROJECT_ROOT"
SEED="$SEED" python3 boomscan_forensics_extended.py \
    --token "$TOKEN_CONTRACT" \
    --export-csv \
    --export-html \
    --output-dir "$OUTPUT_DIR"

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo -e "${RED}❌ Analysis failed with exit code $EXIT_CODE${NC}"
    exit $EXIT_CODE
fi

# Create README for client
cat > "$OUTPUT_DIR/README.txt" <<EOF
Blockchain Forensics Report
Generated for: $CLIENT_NAME
Date: $(date +"%Y-%m-%d %H:%M:%S")
Token: $TOKEN_CONTRACT
Analysis Seed: $SEED

FILES INCLUDED:
===============

1. forensics_report.html
   - Professional HTML report with interactive metrics
   - Open in any web browser
   - Suitable for presentation to stakeholders

2. transfers.csv
   - Raw transfer data used in analysis
   - Import into Excel/Google Sheets for further analysis
   - Columns: tx_hash, from_address, to_address, value, timestamp, etc.

3. analysis_summary.csv
   - Summary metrics in CSV format
   - Top addresses by count and volume
   - Concentration ratios
   - Top transfer pairs

4. ANALYSIS_RESULTS.md (if generated)
   - Detailed technical report
   - Methodology explanation
   - Evidence documentation

REPRODUCIBILITY:
================
To reproduce this exact analysis, use seed: $SEED

Command:
  SEED=$SEED python3 boomscan_forensics_extended.py \\
    --token $TOKEN_CONTRACT --export-all

NEXT STEPS:
===========
1. Review forensics_report.html for executive summary
2. Check confidence score and classification
3. Review detailed metrics in CSV files
4. Refer questions to security team

For technical details, see ANALYSIS_RESULTS.md

Generated by: Blockchain Forensics Analyzer v1.0
Project: AINative Platform
Contact: security@ainative.com
EOF

# Create summary
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}✅ Report Generation Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${BLUE}Output Directory:${NC}"
echo "  $OUTPUT_DIR"
echo ""
echo -e "${BLUE}Files Generated:${NC}"
ls -lh "$OUTPUT_DIR" | tail -n +2 | awk '{print "  " $9 " (" $5 ")"}'
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Open: ${OUTPUT_DIR}/forensics_report.html"
echo "  2. Review confidence score and verdict"
echo "  3. Check ${OUTPUT_DIR}/README.txt for details"
echo ""
echo -e "${YELLOW}Reproducibility Seed: $SEED${NC}"
echo -e "${YELLOW}(Save this seed to reproduce exact results)${NC}"
echo ""
